version: '3.1'
services:
    db:
        image: 'mariadb:10.6'
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DB_NAME}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - '${MYSQL_PORT}:3306'
        volumes:
            - ./dump:/docker-entrypoint-initdb.d

    web:
        image: 'nginx:alpine'
        working_dir: /app
        volumes:
            - './app/src:/app'
            - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '${HTTP_PORT}:80'

    backend:
        build: docker/php-fpm
        working_dir: /app
        volumes:
            - './app:/app'
